### ISSUE TITLE
Cannot run test suite

### ISSUE THREAD

**Issue by MasterOdin** [asciidoc3/asciidoc3-deprecated#7]
Get an error when attempting to run the test suite:
```
root@ee10a92b43d4:/srv/asciidoc# python3 tests/testasciidoc3.py update
Traceback (most recent call last):
  File "/srv/asciidoc/asciidoc3.py", line 6042, in asciidoc3
    if not config.load_from_dirs('asciidoc3.conf', include=['attributes']):
  File "/srv/asciidoc/asciidoc3.py", line 5252, in load_from_dirs
    if self.load_file(f, include=include):
  File "/srv/asciidoc/asciidoc3.py", line 5127, in load_file
    while not rdr.eof():
  File "/srv/asciidoc/asciidoc3.py", line 4849, in eof
    return self.read_next() is None
  File "/srv/asciidoc/asciidoc3.py", line 4853, in read_next
    result = self.read()
  File "/srv/asciidoc/asciidoc3.py", line 4844, in read
    result):
  File "/srv/asciidoc/asciidoc3.py", line 4271, in match
    if re.match(name, mo.group('name')):
  File "/usr/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.6/sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \i at position 28

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/asciidoc/tests/asciidoc3api.py", line 224, in execute
    self.asciidoc3.execute(self.cmd, opts.values, args)
  File "/srv/asciidoc/asciidoc3.py", line 6316, in execute
    asciidoc3(backend, doctype, confiles, infile, outfile, options)
  File "/srv/asciidoc/asciidoc3.py", line 6175, in asciidoc3
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testasciidoc3.py", line 433, in <module>
    tests.update(number, backend, force=force)
  File "tests/testasciidoc3.py", line 344, in update
    test.update(backend, force=force)
  File "tests/testasciidoc3.py", line 224, in update
    self.update_expected(backend)
  File "tests/testasciidoc3.py", line 203, in update_expected
    lines = self.generate_expected(backend)
  File "tests/testasciidoc3.py", line 196, in generate_expected
    asciidoc3.execute(infile, outfile, backend)
  File "/srv/asciidoc/tests/asciidoc3api.py", line 229, in execute
    raise AsciiDoc3Error(self.messages[-1])
asciidoc3api.AsciiDoc3Error: FAILED: unexpected error: bad escape \i at position 28
```

**Comment by asciidoc3** [comment]
@MasterOdin,
I was offline for about 14 days (by my own choice - yes indeed this is possible). I‘ll check this within the next few days (this weekend probably) ...

**Comment by asciidoc3** [comment]
https://github.com/asciidoc3/asciidoc3/pull/8#issuecomment-394500158

**Comment by asciidoc3** [comment]
see asciidoc3/asciidoc3
